version: '2'
services:

  # The Application
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/var/www
    links:
      - redis
      - mysql
    environment:
      - "DB_PORT=${DB_PORT}"
      - "DB_HOST=${DB_HOST}"
      - "REDIS_PORT=${REDIS_PORT}"
      - "REDIS_HOST=${REDIS_HOST}"

  # The Web Server
  nginx:
    build: ./docker/nginx
    volumes_from:
      - php-fpm
    ports:
      - "${APP_PORT}:80"

  # The Database
  mysql:
    image: mysql:5.6
    ports:
      - "${DB_PORT}:3306"
    environment:
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}"

  # Redis
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"

